item {
    id: 1
    name: 'Manual'
}
item {
    id: 2
    name: 'Skruepose'
}
item {
    id: 3
    name: 'Skotrende'
}
item {
    id: 4
    name: 'Kappen'
}
item {
    id: 5
    name: 'Underkarm'
}
item {
    id: 6
    name: 'Skumkarm'
}
item {
    id: 7
    name: 'Fugebaend'
}